import Navbar from "@/compnents/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/compnents/Footer/Footer";

//local font
import localFont from "@next/font/local";
const myfont = localFont({ src: "./Graphie-Regular.otf" });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myfont.className}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
